AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-api
  Sample SAM Template for sample-api
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
        PrimaryKey:
          Name: email
          Type: String
        TableName: userdatabase

  SampleAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: flask-api/
      Handler: app.app
      Runtime: python3.8
      Policies:
        - AmazonDynamoDBFullAccess
#        - DynamoDBCrudPolicy:
#            TableName:
#              !Ref UserTable
      Events:
        Home:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /home
            Method: get
        RegisterUser1:
          Type: Api
          Properties:
            Path: /register
            Method: get
        RegisterUser2:
          Type: Api
          Properties:
            Path: /register
            Method: post
        LoginUser1:
          Type: Api
          Properties:
            Path: /login
            Method: get
        LoginUser2:
          Type: Api
          Properties:
            Path: /login
            Method: post
        ResetPassword1:
          Type: Api
          Properties:
            Path: /reset
            Method: get
        ResetPassword2:
          Type: Api
          Properties:
            Path: /reset
            Method: post
        PasswordReset1:
          Type: Api
          Properties:
            Path: /password
            Method: get
        PasswordReset2:
          Type: Api
          Properties:
            Path: /password
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SampleAPIFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SampleAPIFunction.Arn
  SampleAPIFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SampleAPIFunctionRole.Arn